title: asm.foo
author:
  name: Adam Mackie
  email: amackie1@gmail.com
baseurl: ""
url: "asm.foo"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jemoji
theme: no-style-please
theme_config:
  appearance: "auto"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: true
  lowercase_titles: true