title: asm.foo
author:
  name: Adam Mackie
  email: amackie1@gmail.com
baseurl: ""
url: "asm.foo"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jemoji
remote_theme: riggraz/no-style-please
theme_config:
  appearance: "auto"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  lowercase_titles: true